### ISSUE TITLE
初始化多个sdk对象，会导致10008

### ISSUE THREAD

**Issue by smomop** [jinuljt/WeWorkFinanceSDK-py#1]
发现sdk里的类属性ciphers问题，第二次创建会携带第一次的变量，改为实例就没问题了，非常感谢大佬的sdk

**Comment by jinuljt** [comment]
🙏，类属性不应该使用可变对象的。比如 函数变量也不应该使用。除非有意为之。

**Comment by smomop** [comment]
是的,初学者，没注意到这个问题
